---

language: python

sudo: required

env:
  - distribution: solita/centos-systemd
    version:      7
  - distribution: solita/centos-systemd
    version:      latest
  - distribution: jrei/systemd-debian
    version:      9
  - distribution: jrei/systemd-debian
    version:      latest
  - distribution: fedora/systemd-systemd
    version:      latest
  - distribution: solita/ubuntu-systemd
    version:      xenial
  - distribution: solita/ubuntu-systemd
    version:      bionic
  - distribution: solita/ubuntu-systemd
    version:      latest

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'

script:
  - container_id=$(mktemp -t XXXXXXXXXXXX)
  - container_id=$( basename "$container_id" )
  - 'docker run --detach --privileged --rm -e "container=docker" --security-opt seccomp=unconfined --tmpfs /run -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="$PWD":"$PWD" -w "$PWD" --name $container_id $distribution:$version sleep 2d'
  - 'docker exec -it $container_id sh -c "cd tests && pwd && ls -ld ./* ../* ../../* ../../../*"'
  - 'docker exec -it $container_id ./tests/env-prep.sh'
  - 'docker exec -it $container_id sh -c "cd tests && ./test.yml -l localhost -vv"'

