---

language: python

sudo: required

env:
  - distribution: solita/centos-systemd
    version:      7
  - distribution: solita/centos-systemd
    version:      latest
  - distribution: jrei/systemd-debian
    version:      9
  - distribution: jrei/systemd-debian
    version:      latest
  - distribution: fedora/systemd-systemd
    version:      latest
  - distribution: solita/ubuntu-systemd
    version:      xenial
  - distribution: solita/ubuntu-systemd
    version:      bionic
  - distribution: solita/ubuntu-systemd
    version:      latest

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'

script:
  - instance_name=$(mktemp -t XXXXXXXXXXXX)
  - instance_name=$( basename "$instance_name" )
  - >
    docker run
      --detach --privileged --rm
      --env container=docker
      --security-opt seccomp=unconfined
      --tmpfs /run
      --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro
      --volume="$PWD":"$PWD"
      --workdir="$PWD"
      --name $instance_name
      $distribution:$version sleep 2d
  - >
    docker exec -it $instance_name
      sh -c "
        set +e;
        pwd;
        cd tests;
        ls -ld ./* ../* ../../* ../../../*;
        mount;
        cat /proc/cmdline;
        env | sort;
      "
  - >
    docker exec -it $instance_name
      ./tests/env-prep.sh
  - >
    docker exec -it $instance_name
      sh -c "cd tests && ./test.yml -l localhost -vv"

after_script:
  - docker stop "$instance_name"
