---

# tasks file for systemd-timesyncd/tests

- name:  Get timedatectl status
  shell: timedatectl status
  register: timedatectl_status
  changed_when:  False
  failed_when: False
  tags:
    - test
    - assert

- name:  Get systemctl status systemd-timesyncd
  shell: systemctl status systemd-timesyncd
  register: timesyncd_status
  changed_when:  False
  failed_when: False
  tags:
    - test
    - assert

- name: Assert timedatectl status
  assert:
    that: '{{ item.assertion }}'
    msg:  '{{ item.message   }}'
  with_items:

    - assertion: "timedatectl_status.stdout | regex_search('synchronized: yes')"
      message:   "NTP does not appear to be synchronized"

    - assertion: "timedatectl_status.stdout | regex_search('Time zone: {{ default.timezone }}')"
      message:   "Timezone does not match {{ default.timezone }}"

    - assertion: "timesyncd_status.stdout | regex_search('Active:.*running')"
      message:   "systemd-timesyncd does not appear to be running"

    - assertion: "timesyncd_status.stdout | regex_search('Status: .Synchronized to time server')"
      message:   "systemd-timesyncd does not appear to be synchronized to a time server"

  tags:
    - test
    - assert
